### ISSUE TITLE
Implict purchase tracking doesn't work when using Google Play Billing Library

### ISSUE THREAD

**Issue by samruston** [facebook/facebook-android-sdk#776]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Java Version: `1.8`
- Android SDK Version: `29`
- Installation Platform & Verison: `Gradle` version `5.6.4`

## Goals

Implicit purchase tracking events should be sent when a purchase happens inside an Android app.

## Expected Results

What do you expect to happen?

## Actual Results

They aren't sent when using the Google Play Billing Library instead of AIDL.

From InAppPurchaseActivityLifecycleTracker.java

```java
    private static final String SERVICE_INTERFACE_NAME =
            "com.android.vending.billing.IInAppBillingService$Stub";
....
        try {
            Class.forName(SERVICE_INTERFACE_NAME);
            hasBillingService = true;
        } catch (ClassNotFoundException ignored) {
            hasBillingService = false;
            return;
        }
```

The ClassNotFoundException gets thrown and so InAppPurchaseActivityLifecycleTracker never initializes.

A temporary workaround is to manually include the AIDL file so it's available to the Facebook SDK.

**Comment by YOUDAN** [comment]
Thanks for reporting it. It's very valuable to us. 
Seems like there is a change in Google Play Billing service for V2+ and current Facebook SDK does not support it. This feature is critical and we will make the change within next a few major releases.

Thanks again!

**Comment by nes123** [comment]
Any update on that? thanks in advance

**Comment by spacen** [comment]
@YOUDAN any update?

**Comment by ivanz5** [comment]
@YOUDAN any planned updates about this issue? Or at least it's a good idea to add some note in docs that it won't work with newer versions of Billing Library.

**Comment by hex** [comment]
No updates yet?

**Comment by evanforest** [comment]
@YOUDAN is there anything new? I'm stuck, I can't receive any App-In purchase events while using V3 google pay and the facebook android sdk version is 9.0.0. Thanks in advance.

**Comment by mrtcnnccn** [comment]
I have been tracking down all the documentations to find why purchases are not being logged. Tried to debug the code by looking at the source and finally found myself here. 

I am totally amazed about this. One of the biggest companies in the world selling ads still has no support for v3 google play billing library while the other ways are being deprecated. 

The worst part is there is no such warning in any of the documentations about the issue. I totally appreciate it.

**Comment by taacton** [comment]
@mrtcnnccn, it looks like v11, released a couple days ago adds support for v3 Google play billing. Change log [here](https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md?fbclid=IwAR2H8q0Fm8fyINgegvzhWtD52h90aa63iS7nLEOQDATtNxpi6uFCfHYOzxQ)

**Comment by mrtcnnccn** [comment]
> @mrtcnnccn, it looks like v11, released a couple days ago adds support for v3 Google play billing. Change log [here](https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md?fbclid=IwAR2H8q0Fm8fyINgegvzhWtD52h90aa63iS7nLEOQDATtNxpi6uFCfHYOzxQ)

Thanks for that. Has anybody checked it? Is it working correct?

**Comment by ztdr** [comment]
- Both  FBSDKFeatureIAPLogging & FBSDKFeatureIAPLoggingLib2  FG is always return false
- InAppPurchaseAutoLogger.java impl for Google Play Billing V2/V3 Only Support PURCHASE NOT SUBSCRIBE

**FUNNY 11.0.0 CHANGE LOG,  WASTE TIME**

**Comment by maxencehenneron** [comment]
This is worrying, we're getting closer and closer to the deadline to implement google billing v3...

**Comment by suli1** [comment]
Any update?

**Comment by LukevanTricht** [comment]
Still having this issue, extremely frustrating that there has been zero communication around this, as it's a pretty crucial part of the Facebook Ads platform.

**Comment by LukevanTricht** [comment]
> Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? This issue may be closed if no further activity occurs. Thank you for your contributions.

It still desperately needs attention

**Comment by gnoph** [comment]
According the changelog (https://github.com/facebook/facebook-android-sdk/blob/main/CHANGELOG.md), 11.0.0 is supposed to support auto logging of Google billing v2/v3 purchases. However this feature is still default to off in the SDK and cannot be changed. Any updates from the team?

> Expanded support for auto-logging of in-app purchases to support apps that use V2 and/or V3 of the Google Play Billing Library

**Comment by gnoph** [comment]
Repro for `FBSDKFeatureIAPLoggingLib2` feature switch issue (replace <APPID> token with a valid applicationId)

```
curl "https://graph.facebook.com/v11.0/<APPID>/mobile_sdk_gk?fields=gatekeepers&format=json&sdk_version=11.3.0&sdk=android&platform=android" -H "ContentType: application/x-www-form-urlencoded" -H "User-Agent: FBAndroidSDK.11.3.0"
```

**Comment by henry-dreamo** [comment]
Are there any updates?

**Comment by LukevanTricht** [comment]
Any more informationj about this?
